### ISSUE TITLE
Image won't run on any vm

### ISSUE THREAD

**Issue by DrKoneko** [holoiso-eol/holoiso#104]
So I tried on VMware workstation pro, virtualbox, and Microsoft hyper-v. Nothing works. Let me know if there is a way to make it work.

**Comment by sbuller** [comment]
```
$ qemu-system-x86_64 -m 2048 -bios /usr/share/ovmf/OVMF.fd -cdrom SteamOS_Holo-20220509_1021_amdgpu-x86_64.iso disk.img
```
The long of it is: it seems that booting is only supported with UEFI.

**Comment by theVakhovskeIsTaken** [comment]
You need a VM with UEFI support, plus why would you run this in unaccelerated environment?

**Comment by DrKoneko** [comment]
I don't have any PC that will allow this to boot. My laptop and PC don't see it as an option to boot from the USB, and my old 2000s computer won't boot it even though it sees the option.

**Comment by ubergeek77** [comment]
@theVakhovskeIsTaken 

Generation 2 Hyper-V VMs do use UEFI, so "not using UEFI" does not appear to be the issue here. There seems to be a few oddities with how holoiso tries to boot under Hyper-V:

- The installation media won't boot with the `linux-neptune-dri` kernel under Hyper-V. It states it can't find the `HOLO_202205` disk by its label, then drops into a shell that cannot be interacted with (force shutdown is required).
  - `core` is the default selection for the installation media anyway, and the installation media will successfully boot with the `core` kernel. It installs successfully with no errors that I can see.
  - The installation configures GRUB to boot with `linux-neptune-dri` by default, despite that not being used for the install. Booting like this will print similar errors about not being able to find the partition for `/` by UUID*, then dropping into a shell that cannot be interacted with (force shutdown is required).
- As `linux-neptune-dri` is broken, the user must enter GRUB's advanced boot options and boot with the `Linux linux` entry.
  - This will simply hang at `Loading initial ramdisk ...` with no further messages whatsoever. The same is true for the `fallback` version of `Linux linux`.
  
  _*I also attempted to boot `linux-neptune-dri` by creating an `/etc/fstab` that uses device names instead of UUIDs (i.e. `/dev/sda2`), but this did not work either._

> plus why would you run this in unaccelerated environment?

I'm not trying to use this to play games. I am helping to maintain software compatible with the Steam Deck, but I won't have one for at least another month, and I need an environment to test in. In particular, I need to test the Steam Deck UI's window switcher, because it's not working for our app and I'm trying to figure out why. I don't care if it's slow, I just need something that's good enough to test with.

Is there anything I can do to get this running on Hyper-V?

**Comment by sbuller** [comment]
> I'm not trying to use this to play games. I am helping to maintain software compatible with the Steam Deck, but I won't have one for at least another month, and I need an environment to test in.

Very yes. I also was trying to do something similar, but I ended up moving on to other projects instead.

**Comment by deftdawg** [comment]
Virtualbox does work for desktop mode see https://github.com/theVakhovskeIsTaken/holoiso/issues/27#issuecomment-1157225513
