### ISSUE TITLE
Unable to install different kernel

### ISSUE THREAD

**Issue by mjkl-gh** [holoiso-eol/holoiso#126]
Since i'm using an intel device (gpd win 3) I would prefer to install a newer kernel. However, installing the current stable kernel through

`pacman -S linux `

Does something weird. It look like it successfully installs, but vmlinuz-linux is still missing from the /boot folder. Moreover, mkinitcpio does not detect the newly installed kernel and will not generate a new initramfs.

I've also tinkered with the recovery image, but was able to install different kernels and run them from there. I noticed when using the recovery image that SteamOs3 is using Dracut rather than mkinitcpio. So I tried a fresh install with dracut. Dracut detects both kernels and generates initramfs's for both the steamdeck kernel and the stable kernel.

However, when I view the contents of the /boot folder vmlinuz-linux is still missing. update-grub doesn't pick it up and I'm obviously unable to run the newer kernel.  

Any idea on what is causing this?

**Comment by d-vandal** [comment]
Hey @mjkl-gh, I ran into this today while trying to get this setup on my vm server.
My work-around was to edit the holoinstall script before running it to remove the following packages from the base install, on line 87:
`pacstrap -i ${HOLO_INSTALL_DIR} base base-devel ${UCODE_INSTALL} core/linux core/linux-headers linux-neptune-dri linux-neptune-dri-headers linux-firmware`

From this line, remove:
`linux-neptune-dri linux-neptune-dri-headers `

The script is located under `/usr/bin/`if I remember correctly, but it might be hanging someplace else.
By removing those, it installed the default kernel from core rather than pulling the neptune image.

Hopefully that will get you up and going!

**Comment by mjkl-gh** [comment]
Just noticed on another distro the same problem. I also noticed their install script using core/linux-lts instead of linux-lts. After installing core/linux I had gained a working kernel (5.16)  

Maybe I'm just a noob, but might there be something wrong with the linux package in steams repo's?

Will try core/linux as soon as I get a working install again
