### ISSUE TITLE
can't login to SteamOS (gamescope) session 

### ISSUE THREAD

**Issue by yras245** [holoiso-eol/holoiso#152]
When I'm trying to login to gamescope I getting error 
failed to start Jupiter Controller Firmware Service 
and then it go back to login screen

Im on intel pc

**Comment by ayamasasaki** [comment]
I have the same problem, I have a little performant computer with Intel i5 gn3, AMD Radeon R7 370, and 8 GB Ram but I don't know what, I have a problem with the Vulkan, because I don't know how to install the drivers on the Arch, I try all the methods and nothing on there work, what can I do to open the SteamOS (gamescope).

**Comment by shaun9111** [comment]
> I have the same problem, I have a little performant computer with Intel i5 gn3, AMD Radeon R7 370, and 8 GB Ram but I don't know what, I have a problem with the Vulkan, because I don't know how to install the drivers on the Arch, I try all the methods and nothing on there work, what can I do to open the SteamOS (gamescope).

I don’t believe your GPU is supported. Only RX series and above

**Comment by WTFPCStuff** [comment]
Happened to me. Can't use anything but lowercase letters with the login name. You'll need to re-install make sure your user name is all lower case. There won't be a warning if you do this wrong, it'll just get stuck on the Jupiter BIOS error. Adding a user also didn't work for me, I had to re-install.
