### ISSUE TITLE
Switch to Debian?

### ISSUE THREAD

**Issue by kogatoerigotsun** [holoiso-eol/holoiso#181]
I think debian is more user-friendly out of the box, and is probably what valve is going to use for 'outofthebox' SteamOS

**Comment by Mario-119** [comment]
The whole point of switching to Arch is that they could make it more user friendly for the end user since they can roll out updates and fixes seamlessly due to the rolling release structure of Arch. All of their new packages are built for Arch, so switching to Debian would completely break them.

**Comment by kogatoerigotsun** [comment]
> The whole point of switching to Arch is that they could make it more user friendly for the end user since they can roll out updates and fixes seamlessly due to the rolling release structure of Arch. All of their new packages are built for Arch, so switching to Debian would completely break them. 

Yes, however debian is more **user friendly**

**Comment by theVakhovskeIsTaken** [comment]
You can switch back to debian at any time you want :)

If you are really sure that it's more user friendly, then start your journey here:
https://store.steampowered.com/steamos/buildyourown

**Comment by ghost** [comment]
> I think debian is more user-friendly out of the box, and is probably what valve is going to use for 'outofthebox' SteamOS

You seem to have missed that Valve just switched from Ubuntu as base for SteamOS2.0 to Arch as base for SteamOS3.0. Or you may have missed the very important part of this repo: This is based upon valves official recovery iso for the real deck hardware to try to make it compatible with regular systems. It's not the maintainer came up with its own steamos - this here is valves stuff - just tinkered with to make it run on a regular pc instead of the deck.

**Comment by theVakhovskeIsTaken** [comment]
I'm not even going to close this issue jesus, this is an awesome gag material.

**Comment by TheRealXyzven** [comment]
> > The whole point of switching to Arch is that they could make it more user friendly for the end user since they can roll out updates and fixes seamlessly due to the rolling release structure of Arch. All of their new packages are built for Arch, so switching to Debian would completely break them.
> 
> Yes, however debian is more **user friendly**

What does that mean?  Can you quantify that?  Are you referring to the user-based support that gives it the more "user friendliness"?   

Everything linux is CLI driven be it Debian, Ubuntu, Redhat, Fedora, Arch, Manajro, etc.  CLI is not idiot/lazy-friendly at all.  However the CLI is user-friendly.  It uses words, is documented, has help (with the "-h" option) and can be utilized by any user.

If you are referring to "ease of use" or "ease of configuration" then even that is arguable.  If you are refering to a DE, again, subjective and argumentative.  Mario-119 states very clearly from a update POV, Arch is much more user friendly than Debian as the rolling updates are incremental rather than bulk.  This allows for a faster response to zero day issues (security or otherwise), and a more seamless experience with troubleshooting.  It also forces the community to be supportive at all times instead of trolls who say "go back 6 months to 2 years back and find the same issue".  So this is where Arch wins IMO.

Also, how is this an issue with this project?  If you want SteamOS to go back to Debian, take it up with Valve and not @theVakhovskeIsTaken project.

**Comment by HyperN00B** [comment]
Arch is waaaaay better. If it breaks, the 1000 online guides can actually teach you how to fix it rather than the Debian way of "reinstall and it will work". If Arch is handled with care, it beats the living hell out of every Debian based distro. (including Ubuntu which is basically the Windows 8 of Linux at this point)

**Comment by alchemistake** [comment]
Dude you wouldn't be able to comment "I use arch btw." on reddit.

**Comment by Gecked-Deck** [comment]
No. That's not what this project is even remotely about.

**Comment by Grimish-ng** [comment]
Wow.. I'm really confused why someone would ask this and put themselves in the cross hairs for something other than it has already been done. Arch is like... capable of everything that all other distros lack. Of course thats my opinion from having SSL problems with Cent, hating debian/ubuntu default package manager (among other things) and yes of course Cent & Redhat have a place in my heart... they lag way far behind. All of linux is great. Every distro has its ups and downs, except of course Arch 👍

**Comment by SaulGoodman1337** [comment]
> > The whole point of switching to Arch is that they could make it more user friendly for the end user since they can roll out updates and fixes seamlessly due to the rolling release structure of Arch. All of their new packages are built for Arch, so switching to Debian would completely break them.
> 
> Yes, however debian is more **user friendly**

This answer **disqualifies you directly**.
