### ISSUE TITLE
Retry upon network failure?

### ISSUE THREAD

**Issue by rikumi** [holoiso-eol/holoiso#182]
Currently the `pacstrap` and `pacman` commands are not wrapped by any error handling, which will cause the whole installation progress to fail.

In such cases, we can't simply re-run the script since the volumes are already mounted. Only modifying the script by hand or rebooting can help, but due to various network conditions, rebooting may not always do the thing right.

Also, there might be issues when users don't even know this error and continue with the script.

Adding an error handling logic around these network-dependent commands should be a better way.

**Comment by rikumi** [comment]
My network condition is so bad that I have no choice but file an issue here. I tried modifying the script every time it fails, but that led to an unbootable system which is always waiting for my hard drive to appear, which may be because of my modified script did something repeatedly.

**Comment by Mrpuppyz** [comment]
I had a similar issue. I had to download off a hotspot with slow speeds. When pacstrap or pacman failed to download it is not always super clear something went wrong because the script continues to do it's thing. I solved the problem by manually adding cache files to the /var/pacman/pkg/ file from my arch install. Then I also edited the pacman.conf to change it to download the files I didn't have only one file at a time rather than the default 5. With this change it was less likely to not fail download. 

Also the script can be edited to # out all the lines that wipe and wright the partitions to the drive so when the script is ran again it doesn't delete all the files it took forever to download that will need to be redownload.

**Comment by skleffmann** [comment]
There is a very simple and convenient solution to this.

After booting from the USB Stick edit the pacman.conf inside /etc, uncomment and edit the XferCommand with the curl command as follows:

XferCommand = /usr/bin/curl --connect-timeout 60 --retry 10 --retry-delay 5 -L -C - -f -o %o %u 

Worked absolutely fine on several install attempts on different systems on my network.
