### ISSUE TITLE
Deck UI Keeps Looping After Verify and Boot Animation

### ISSUE THREAD

**Issue by DoctorValor** [holoiso-eol/holoiso#206]
After the Grub.cfg update for Nvidia gpus, I have finally been able to get gamescope to actually boot. However, after a good 30 seconds, the Steam Deck's "Verifying System" screen will appear, and then will attempt to go through the boot animation. This only plays for half the animation before going to black, and then the process repeats. I'm running this install from a 256gb USB-3 portable SSD, so I suspect this could possibly be an issue, but was hoping to confirm before sacrificing a proper internal drive for the install.

Hardware:
GTX 1070
i7-7700
16gb DDR4 RAM

**Comment by DoctorValor** [comment]
This actually resolved itself after a couple reboots. Huzzah I guess?

**Comment by jrcharney** [comment]
Just a followup: After you mentioned that it started working again after a couple of reboots (in that it ran the bootloading animation a few times...[neuralyzed](https://www.youtube.com/watch?v=wqlFiTOi6QQ) my mind each time as well which started with a white square before a white flash and the bootloading animation ran again.)  It ran a few times before finally something kicked in to make it download about a 200 MB file (likely the latest upgrade) because all sorts of things were broken with Steam.

Honestly, someone should fix that so their photosensitivity issues don't kick in (especially if a user has epilepsy) or if by chance they were actually 😎 [MESSAGE REDACTED] 😎 Swamp Gas/Weather Balloons/Experimental Aircraft.  But who's going to believe that?
