### ISSUE TITLE
gpd win 2 blank screen

### ISSUE THREAD

**Issue by houku** [holoiso-eol/holoiso#225]
so i looked at a lot of issues for this, i installed the master branch since the latest stable was way out of date, and i tried the intel tester option, but it still was blank screen, i thought it might just be slow at showing the icon since its like that also with some other distros, but it didnt load, before snapshot 5 i was able to get it working with the SteamOS_Holo-20220522_1750_amdgpu-x86_64 but even that now gives blank screen, the any help to get steamOS 3 on my gpd win 2?

thanks in adnvace and great work! i love what you are doing (and i love your cute emojis you add, adds cuteness that i like)

**Comment by theVakhovskeIsTaken** [comment]
Can you try this one? https://github.com/theVakhovskeIsTaken/holoiso/releases/download/snapshot20220526.1355-1/SteamOS_Holo-20220527_0803_amdgpu-x86_64.iso

**Comment by Deen0X** [comment]
im testing (20220527_803) on win1 and win2, and get the same result
i uploaded a videolog of the install on win1.
https://youtu.be/_ObLCL1fT6c
Im testing now on WIN3 and i have the same behavior. 
sorry if i can´t bring to you more info. im not a linux guy, Let me know if you need something from my part to help to you to develop this iso for GPD devices (intel integrated CPUs)

**Comment by houku** [comment]
i uploaded a videolog of the install on win1. https://youtu.be/_ObLCL1fT6c 

In your video you show how to get to kde plasma, does going to game mode work from there? If not, did you get the game mode working? If so, how?

**Comment by Deen0X** [comment]
nope. if i try to launch from desktop, nothing happens.
If i try to run from command line:
steamos-session-select
the system respond:
are you running SteamOS on KDE Plasma or SteamOS Session?

i figure the TTY1 is running some plasma session, but with black screen. i don´t know how to kill this, or how to fix the launch command.

if i try running the command:
gamescope
the output is:
wlserver: [libseat] [libseat/bakcend/seatd.c:80] could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/bakcend/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/bakcend/libseat.c:73] Seat opened with backend 'logind'
wlserver: [libseat] [backend/session/session.c:110] Successfully loaded libseat session 
vulkan: vkCreateInstance failed (VkResult: -9)
Failed to initialize Vulkan

I figure the problem is (obvious) Vulkan.
Im on my office, and there i have only GPD-WIN1 device, for testing.

**Comment by houku** [comment]
In snapshot 5, go to the plasma desktop with startplasma-wayland and from there run those commands

sudo pacman -S gamescope vulkan-intel-steamos lib32-vulkan-intel-steamos mesa-steamos lib32-mesa-steamos

Then: pacman -S extra/mesa multilib/lib32-mesa holo/gamescope

Then reboot and it fixed for me aside that steamOS 3 can't update to 3.2

**Comment by Deen0X** [comment]
ok. i will re-install snapshot 5 and test your suggestion.
