### ISSUE TITLE
Adapting the current SteamOS Fan Curve for Steam Deck

### ISSUE THREAD

**Issue by NightHammer1000** [holoiso-eol/holoiso#246]
HoloISO would be my go to Distro for the Deck, Especially the Unlocked Filesystem is very nice for someone like me who absolutly hates Flatpak.

But with my Testing I found that the Fan Curve in HoloISO is quite more aggressive than stock SteamOS.

Would it be possible to adapt the Fan Curve from stock SteamOS?

**Comment by theVakhovskeIsTaken** [comment]
Hmmm. Nice to see actual SDeck users, even if it's pointless. I don't know honestly, i haven't downloaded latest SDeck update image. But you can try installing sudo pacman -S linux-jupiter and then do sudo grub-mkconfig -o /boot/grub/grub.cfg as i believe, that's being done on kernel side

**Comment by NightHammer1000** [comment]
Its not so pointless. 
The Locked System Partition, that wipes all the User installed packages on each update is annoying as hell for an old Linux Dog like me.

Flatpak brings more Issues than its worth imo. 
So this is a welcomed, pretty much vanilla SteamOS Solution for me.

I will try out your suggestion and report back.

**Comment by baodrate** [comment]
The program that manages the fan in Steam Deck's stock OS is in the `jupiter-fan-control` package in the [`jupiter` repo on Valve's pacman mirror](https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/). Should be installable from the "Holo" system you have. It's just a few files:

```
deck@holo ~ % pacman -Ql jupiter-fan-control
jupiter-fan-control /usr/
jupiter-fan-control /usr/lib/
jupiter-fan-control /usr/lib/systemd/
jupiter-fan-control /usr/lib/systemd/system/
jupiter-fan-control /usr/lib/systemd/system/jupiter-fan-control.service
jupiter-fan-control /usr/lib/systemd/system/multi-user.target.wants/
jupiter-fan-control /usr/lib/systemd/system/multi-user.target.wants/jupiter-fan-control.service
jupiter-fan-control /usr/share/
jupiter-fan-control /usr/share/jupiter-fan-control/
jupiter-fan-control /usr/share/jupiter-fan-control/PID.py
jupiter-fan-control /usr/share/jupiter-fan-control/fancontrol.py
jupiter-fan-control /usr/share/jupiter-fan-control/jupiter-fan-control-config.yaml
```

It's enabled by default on install (because of the link in `/usr/lib/systemd/system/multi-user.target.wants/`) but you'll want to `systemctl start jupiter-fan-control` or reboot to start it up. I haven't tested this (only running stock SteamOS on by hardware Steam Deck, Holo is only running in a VM), but it should work.

**Comment by NightHammer1000** [comment]
Indeed it does!
Nice. Thanks
