### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by F0R3V3R50F7** [holoiso-eol/holoiso#28]
After installation and reboot I have a GUI login screen, I enter password and nothing happens. Session list is empty.

**Comment by nisehime** [comment]
Are you running it in virtualbox?

**Comment by TTR-IND** [comment]
No, I am running it on a Dell WYSE 5060

AMD GX-424CC SOC with Radeon R5E Graphics

**Comment by nisehime** [comment]
Ok. I have the same issue on Vbox.

**Comment by XargonWan** [comment]
Same, after the login I am bumped back to the login screen after seeing this otuput:

![VirtualBox_SteamOS Holo_07_05_2022_11_40_01](https://user-images.githubusercontent.com/6771419/167234809-62fd4693-ee40-4b12-9b01-6ef8f79b3b0a.png)

**Comment by TTR-IND** [comment]
I'm thinking our GPUS or in the other chaps case, our virtual GPUs are lacking VDPAU support but there's so little information on mine around I had to submit it to Techpowerup myself so I have no idea. It was worth the shot but I think I'll go down the road of heavily modifying manjaro instead. Perhaps you two would like to give it a try, best of luck!

**Comment by nisehime** [comment]
It might be the problem in the build itself. I tried other one, and there was a session in the list and I was able to login now (only in desktop mode however, gamescope didn't work). But again, I'm on virtualbox.

@XargonWan 
In our case when we enter password there's no reaction at all. Because there's no sessions for some reason.

**Comment by cynetzhan** [comment]
Had the same issue. Session list empty, cant login. 

When installer is downloading packages (the third round where total download is 1.5GB), one of the package is failed to download, and I think the installer didn't retry downloading or installing the other downloaded package (the counter stop at around 30-40 package out of 500-ish package to download). If im not mistaken it stopped when try downloading gwenview package. Maybe it caused by that?

**Comment by danieljgmaclean** [comment]
I've the same issue with VirtualBox and Parallels i.e. reach the login screen, no sessions in the dropdown, and after entering my password nothing happens.

So I just installed plasma manually and i'm in now, these are the commands I used:

```
pacman -S --needed xorg sddm
pacman -S --needed plasma
```

This will get you into KDE, but not gamescope. You'll need to install zsh and gamescope manually:

`pacman -S --needed zsh gamescope`

But for me at least, it will ultimately not work because the Parallels Virtual GPU for linux only supports OpenGL2 and not Vulkan, so when I ran gamescope I got:

```
SDL_Vulkan_LoadLibrary failed: Installed Vulkan doesn't implement the VK_KHR_surface extension
Failed to initialize Vulkan
```
