### ISSUE TITLE
Any way of changing the main display?

### ISSUE THREAD

**Issue by dashwr** [holoiso-eol/holoiso#313]
Gaming mode defaults to my laptop's internal display, which is half broken and a pain to game on.
Is there any way of fully disabling it so gaming mode only detects my external monitor? Thanks a lot.

Nice work by the way. I've been wanting to install SteamOS ever since i knew it ran on Arch, and this was perfect and very easy to install.

**Comment by dashwr** [comment]
For anyone with the same problem, you can look towards editing /etc/default/grub.

Run the command below in the terminal to get the names of your displays:
```
xrandr --query | grep 'VGA\|HDMI\|DP\|LVDS'
```
(If it's an internal display, chances are it'll show up as DP, eDP or LVDS and connected)

Then open `/etc/default/grub` with a text editor and place `video=internaldisplayhere:d` within `GRUB_CMDLINE_LINUX_DEFAULT` to disable the display specified in place of "internaldisplayhere".

Hope this helps anyone, considering it's not an easy task to find updated fixes for oddly common problems on Linux.

**Comment by Bryan199234** [comment]
I'm extremely new to Linux and have just recently gotten one of the HoloISO revisions to finally mount correctly as a separate bootable OS. Its working quite well when there is a dedicated display connected to it, however, I am trying to run this as a headless rig. When using Remote Play via Steam Link, my session displays as backlit black. I know everything is working correctly (off screen?), because I can hear UI tones sounding when sending inputs.

Found this thread assuming that this is a related issue. But due to my lack of understanding the above instructions, I became confused fast. In my grub file, I have GRUB_CMDLINE_LINUX_DEFAULT listed multiple times throughout the script. Am I supposed insert video=internaldisplayhere:d deliberately within each line that calls this out? Also, where am I supposed to find the callout for "internaldisplayhere". The txt file contains my existing external displays (DP2 will show as disconnect because it is attached to KVM. DP1 is a dead-end DP, used for my Windows boot), ideally I would like the default when running in GameMode to be whatever the outgoing video source happens to be when Streaming to Steam Link.
[External Displays.txt](https://github.com/theVakhovskeIsTaken/holoiso/files/10928068/External.Displays.txt)

**Comment by 164KiloBytes** [comment]
Where do insert the text?
