### ISSUE TITLE
Are there any installation guides for installing in VirtualBox?

### ISSUE THREAD

**Issue by baschgan** [holoiso-eol/holoiso#330]
I tried to install as efi but stuck in terminal

**Comment by wynn1212** [comment]
If you trying to install Holoiso in Virtualbox. It won't work because gamescope not support VMSVGA graphics card.

**Prerequistes:**
- 4GB flash drive
- ### AMD RX Vega+/APU iGPU; 4xx/5xx, 5xxx/6xxx GPU or Intel UHD 630+ iGPU or NVIDIA GTX 9xx+ iGPU/GPUs (preferably without Optimus [PRIME])
- UEFI-enabled device
- Disabled secure boot
