### ISSUE TITLE
Boots into tty mode

### ISSUE THREAD

**Issue by Abhs15** [holoiso-eol/holoiso#333]
I'm having a problem where after i boot into steam os all i get is a tty screen ever time i'm using AMD gpu and cpu. after installation when it boots into tty i tought that sddm wasn't enabled so i enabled it on the command line but after that it just boots into a black screen when i boot into the installer and try to access arch-chroot /mnt it shows an error saying that /mnt isn't  a mount point.I have tried flashing the iso to another flash still the same issue is there anything i can do to fix this.

**Comment by ZombieBear** [comment]
/mnt isn't mounted on boot of the installation media, this is only after the installation is performed, as it's mounted for the install process.
You'll want to run fdisk -l to determine the partition you installed the OS into and then mount the drive in order to be able to run the command
For example if you're installed into /dev/sda2, the mount command will be mount /dev/sda2 /mnt
Once the drive is mounted, you can cd into the directory and run ls to ensure it's the right partition and once you've confirmed that, you can run the arch-chroot command

**Comment by Abhs15** [comment]
tnx chroot works now but how can i fix the tty problem i have tried enabling sddm but it just boots into black screen so is there anything else i can try.

**Comment by Smee342** [comment]
> tnx chroot works now but how can i fix the tty problem i have tried enabling sddm but it just boots into black screen so is there anything else i can try.

I was getting a black screen also. Question your username and password you set when installing from holoiso are they all lowercase without numbers? I had to reinstall and use only lowercase letters for my username and password to get passed the black screen.

**Comment by Abhs15** [comment]
Ya all are lower case letters.im going to try snapshot 5 iso some say that this one worked for them so i will try that and update you if it works.

**Comment by Abhs15** [comment]
sadly it didnt work not even after mounting in /mnt  chrooting failed i think the problem is that /mnt wasnt created or something b/c it says /mnt doesnt exist how cani fix this

**Comment by Abhs15** [comment]
in the newest snapshot this issue have been fixed for those who have the same problem build the newest snapshot version 20220711.1512 it should fix it tnx

**Comment by Abhs15** [comment]
in the newest snapshot this issue have been fixed for those who have the same problem build the newest snapshot version 20220711.1512 it should fix it tnx
