### ISSUE TITLE
external monitor for SteamOS

### ISSUE THREAD

**Issue by LightRO** [holoiso-eol/holoiso#345]
Hello all,
I have a laptop and the SteamOS runs only on the internal display. But I would like to connect this to the TV via HDMI. 

In the grub I have already added the setting "video=eDP-1:d" but unfortunately without effect.

Can someone help me further.

**Comment by PIPIPIG233666** [comment]
Switch to desktop, then set up your monitor from there.

**Comment by LightRO** [comment]
I've already tried that, but it's only for desktop mode and not for the Steam GUI. This actually does not change. The desktop mode is a hindrance because I always need a mouse and keyboard for this and the laptop is always open. 

There must be a way for the SteamOS GUI to start on a different monitor.

**Comment by LightRO** [comment]
After the SteamDeck OS update, it now works if you follow the steps below:

1.) Follow the steps from this guide: https://github.com/theVakhovskeIsTaken/holoiso/issues/313

2) Do a SteamdeckOS update in the SteamOS GUI and it will accept the new settings from the grub.

**Comment by augustoicaro** [comment]
I tied your steps, but no luck. I installed my holoiso with my second monitor connected and the default monitor for gamescope is the second monitor. The problem is even worse because when I disconnect the second monitor gamescope doesn't show up, with no sound and black screen. The monitor in the desktop display settings appears as do not use, but gamescope still doesn't respect the configuration.

**Comment by augustoicaro** [comment]
Studying more about my problem I discovered on the gamescope log that my Nvidia card only have DRM connection to DP or hdmi and only the integrated card have the DRM to the laptop monitor. That's why every attempt to use the laptop monitor in gamescope failed. In  https://github.com/theVakhovskeIsTaken/holoiso/issues/511 I learned how to set the prefered card.

Now I have one more reason to buy laptops with tux switch, so I can disable completely the integrated graphic card.
