### ISSUE TITLE
Stuck on loading intial ramdisk (holoiso-disable-sessions doesn't work)

### ISSUE THREAD

**Issue by malefactor666** [holoiso-eol/holoiso#382]
## Your Issue:
```
On initial boot, gets stuck on "loading intial ramdisk".
Boot into recovery > run "holoiso-disable-sessions" > reboot > get to logon screen with no usernames to select
```

## Your device's full specs
```
CPU: Ryzen 3 3100
GPU: GTX 1660
```

**Comment by CorValidum** [comment]
Same here... I could not even boot in to recovery... Funny enough I was able to install fine and log in to Steam. Only when I clicked on Steam in lover left corner after introduction to on screen options it started happening and since then I am unable to do anything xD


Legion 5
CPU: Ryzen 5 5600H
GPU: RTX3070

**Comment by malefactor666** [comment]
I'm thinking this must have something to do with Nvidia drivers as the same release worked fine on a machine running and AMD GPU

**Comment by BonQerss** [comment]
any solution?

**Comment by colingoodman** [comment]
Having the same problem with a Nvidia GPU, GTX 970
