### ISSUE TITLE
[Report]Two updates does not work.

### ISSUE THREAD

**Issue by agentwolf88** [holoiso-eol/holoiso#386]
There are two updates they cant install. What can i do?

Intel i5 10600k
16GB Ram
RTX 3070

![2022-07-20_21-11](https://user-images.githubusercontent.com/9948479/180063689-aa958dfd-e7ba-4151-956d-2ade2010bb12.png)
![2022-07-20_21-11_1](https://user-images.githubusercontent.com/9948479/180063705-6d67f636-ac78-47c5-9178-cfb81dfcab6e.png)

![2022-07-20_21-16](https://user-images.githubusercontent.com/9948479/180064027-36e29749-6c44-4593-a878-d03c036bf7af.png)

**Comment by alansari** [comment]
uncheck holoiso-main and only update the updateclient, then try again from deckui or discover and it will work

**Comment by samiscool51** [comment]
> uncheck holoiso-main and only update the updateclient, then try again from deckui or discover and it will work

i've unfortuently tried this and it also failed, i thought it was due to open-vm-tools screwing with the system (since i'm running this in a vm) at the time since i was unable to find an issue describing it.
at least it's nice to know that might not be the problem.
i managed to force the system to update by using `sudo pacman -Syu --overwrite=*` but i did it as a last resort since i can't boot up the deckui to update the system, the system _seems_ fine but something is gonna bite me in the ass latter down the line.

**Comment by agentwolf88** [comment]
> uncheck holoiso-main and only update the updateclient, then try again from deckui or discover and it will work

"updateclient updated fine now, but holoiso-main still not update.

**Comment by godtoall82** [comment]
Any fix to this? Ran into the same issue and haven't found a way to update holoiso-main
