### ISSUE TITLE
download link doesn't work well, how can i build the iso by source so i can run it on virtual machine

### ISSUE THREAD

**Issue by Toni500github** [holoiso-eol/holoiso#421]

**Comment by 8-BrickDMG** [comment]
I had this same issue earlier today. I had to open Edge browser and it downloaded fine there.

**Comment by Toni500github** [comment]
> I had this same issue earlier today. I had to open Edge browser and it downloaded fine there.

for linux works though?

**Comment by Toni500github** [comment]
Nvm, I downloaded it on my phone for then move it via usb on my pc

**Comment by ChaosBlades** [comment]
Not sure what the deal is with the download link or why it is a link in the first place instead of just an asset but I can't get it to work at all on Brave Browser. I even try to open it as a new tab and the tab just closes.

I ended up having to open terminal and run `wget http://thevakhovske.pw/dl/holoiso-stable` in order to download it.

**Comment by SamusAranX** [comment]
It's because the link is HTTP. Chrome and Chrome-derived browsers won't allow you to download anything from HTTP links when they're on HTTPS pages.

This is most likely user error on the repo owner's part because while thevakhovske.pw supports HTTPS, it doesn't auto-redirect from HTTP to HTTPS for some reason. Obviously, a better solution would be to simply attach the asset to the GH release. As long as it stays under 2 GB that shouldn't be a problem. @theVakhovskeIsTaken
