### ISSUE TITLE
Iwctl / Iwd crashing when setting up wifi for holo install

### ISSUE THREAD

**Issue by Basketballforce** [holoiso-eol/holoiso#434]
## Your Issue:
```
*Iwctl / Iwd crashing. Wifi pops/toggles on and off repeatedly when attempting to connect for first time install*
```

## Your device's full specs
```
CPU: Ryzen 5600G APU
GPU: Ryzen 5600G APU
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
HoloISO_Stable_GUI-20220719_2019-x86_64.iso
```

## Your installation type
```
Deckexperience
```

## My Fix/Resolving the issue
I played around with debugging the wifi related systemctl services but couldn't get a consistent solution until following a debug thread from [https://bbs.archlinux.org/viewtopic.php?id=236562](https://bbs.archlinux.org/viewtopic.php?id=236562)

To fix my issue I used 2 commands
1. Disable or mask the dhcpcd service (this example masks it)

```Systemctl mask dhcpcd.service```

2. Turn on the iwd service
```Sudo systemctl start iwd```

3. You may then need to use the gui interface to toggle the wifi on and off once or twice

Then you should be able to connect to wifi with the gui.

**Comment by PIPIPIG233666** [comment]
It's a known issue, newer firmware will probably be included in the next release according to Mr. V.

**Comment by jrcharney** [comment]
This likely has something to do with NetworkManager butting heads with some other software.  The installer fortunately makes this an easy fix as we just need to tell the NetworkManager to use `iwd` as a back end.  This should also fix `iwd` crashes, especially when you are trying to type in the pass key for the network you are trying to connect.

BTW, `nmtui` is crap.  You try adding a WiFi device (typically `wlan0`) to tell it about the WiFi device and it doesn't update the list of connections in the device selection.  This is why a lot of folks like using `iwctl` instead.

I recommend using `CTRL+ALT+F2` and logging in as `root` to fix this problem. (Don't worry. You can return the to Plasma GUI later with `CTRL+ALT+F7`.)

First thing you'll want to do is check if you have an internal WiFi device using `lspci -nnk`. This will list out all the PCI devices including PCIe, USB, SSD, SATA, and NVMe. 

Next, you'll want to see what services that `systemd` uses.

```
find /etc/systemd -name \*.service -type l -a -xtype f -printf %f\\n | sort
```

If you see `NetworkManager.service` as well as `iwd.service`, `wpa_supplicant.service` or some other service that does WiFi stuff, there's a good chance `NetworkManager` is in conflict with it.  What we will want to do is tell `NetworkManager` to use `iwd` as a backend by creating `/etc/NetworkManager/conf.d/iwd.conf` with a text editor.  This file should have just two lines in it.

```
[device]
wifi.backend=iwd
```

Save that file then run these lines. (Note: the `.service` suffix is optional. I didn't add it to the end of each of these lines.)

```
systemctl stop NetworkManager
systemctl disable --now wpa_supplicant
systemctl restart NetworkManager
systemctl restart iwd
```

These four lines will stop the `NetworkManager`, it will stop the `wpa_supplicant` permenantly, it will restart the `NetworkManager`, and for good measure I added a command to restart `iwd` which if you've had that service crash before hand, this should make that problem go away.

You should then be able to run `iwctl` (the command line interface of `iwd`) to get WiFi set up.  Let's say we have a device `wlan0` and a WiFi Network `Bruce_Campbell_Is_Awesome`. ("Hail to the king, baby!")

First, check your device list to see if `wlan0` exists.

```
device list
```

Next, scan for WiFi network and show the list of networks. You should run both of these lines.

```
station wlan0 scan
station wlan0 get-networks
```

This program will actually live update the list of available connections. But we want to connect to `Bruce_Campbell_Is_Awesome`.  If it is in the list, type this command.

```
station wlan0 connect Bruce_Campbell_Is_Awesome
```

If your network was connected with a passkey (as indicated on the network list with `psk`) enter that.

Finally, show what the status is of that connection if it was successful.

```
station wlan0 show
```

If everything is good, type `exit` to return the the shell.

You can check your connection in the shell using `ip address` (or `ip a` for short) or see the routing table using `ip route` (or `ip r` for short).

Lastly, why not use `curl` to see your IP Address information with `curl ipinfo.io` or see the weather with `curl wttr.in`.  It's sort of a personal preference at the end to do a `curl` command to one of these sites rather than a `ping` to Google. Also those sites are pretty useful in affirming your accomplishment of getting the internet working! (Yay!)

Alright, now all you gotta do is run `holoinstall` and..."SSL_INIT"?  Chances are issue #435 will likely be the next issue you'll have.  The good news is that other people had that same problem, someone else came up with a solution, but [my answer gives it a better explaination as to why that happens](https://github.com/theVakhovskeIsTaken/holoiso/issues/435#issuecomment-1214262121).

**Comment by theVakhovskeIsTaken** [comment]
Next installer release you won't need to use IWD anymore, and just connect using taskbar icon


New firmware will be shipped too.

Noted.
