### ISSUE TITLE
Set TDP on AMD APU

### ISSUE THREAD

**Issue by wmd0701** [holoiso-eol/holoiso#439]
Hi! First, great thanks for making it possible to transplant deck os to other devices. 

In the readme file it is mentioned that TDP and GPU clock limiting doesn't function on APU devices. So it won't work on AMD chips like 6600U, 6800U or 6900HS (or whatever CPUs with RDNA2 iGPU)? I know only very few in this field and I am pretty interested why this is the case since steam deck itself is an APU device... How could it work on some dGPU devices but not on other APU devices?

Again, deep appreciation for the work!

**Comment by danyi** [comment]
I had the same problem with my GPD WINMAX2 6800U
And I want answers

**Comment by danyi** [comment]
I had the same problem with my GPD WINMAX2 6800U

It's the same problem you described

I want answers, too

**Comment by theVakhovskeIsTaken** [comment]
Well, to sort things out first:

1. TDP and clock changing is disabled ENTIRELY os-side, since dGPU performance was cut down by 90%, as Steam Deck client has hard-coded values for TDP/clock changing, ranging from 6000 pts all the way to 20000

2. You can use HandyPT with ryzensmu enabled to change your TDP

3. Why the random compatibiliy? Because Steam Deck's privileged write script isn't unified, and is hardcoded on special kernel node


Hope this resolved all of your questions ^^
