### ISSUE TITLE
[Report] No sound

### ISSUE THREAD

**Issue by poperigby** [holoiso-eol/holoiso#473]
## Your Issue:
Audio devices are detected, but no sound is produced.

## Your device's full specs
```
Processors: 4 × Intel® Core™ i5-6400 CPU @ 2.70GHz
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 480 Graphics
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20220819.0846
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
Yes

## `journalctl -p 3 -xb` output
```
Aug 22 23:23:41 calculus kernel: x86/cpu: VMX (outside TXT) disabled by BIOS
Aug 22 23:23:41 calculus kernel: x86/cpu: SGX disabled by BIOS.
Aug 22 23:23:42 calculus kernel: [drm:detect_link_and_local_sink [amdgpu]] *ERROR* No EDID read.
Aug 22 23:24:19 calculus p-steamos-priv-write[2232]: decline harder: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Aug 22 23:24:19 calculus p-steamos-priv-write[2254]: decline harder: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Aug 22 23:24:20 calculus p-steamos-priv-write[2278]: decline harder: 15000000 -> /sys/class/hwmon/hwmon4/power1_cap
Aug 22 23:24:20 calculus p-steamos-priv-write[2298]: decline harder: 15000000 -> /sys/class/hwmon/hwmon4/power2_cap
Aug 22 23:24:41 calculus systemd[3524]: obex.service: Failed at step EXEC spawning /usr/lib/bluetooth/obexd: No such file or directory
░░ Subject: Process /usr/lib/bluetooth/obexd could not be executed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The process /usr/lib/bluetooth/obexd could not be executed and failed.
░░ 
░░ The error number returned by this process is ERRNO.
Aug 22 23:24:41 calculus systemd[432]: Failed to start Bluetooth OBEX service.
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished with a failure.
░░ 
░░ The job identifier is 194 and the job result is failed.
Aug 22 23:26:09 calculus pipewire[578]: spa.alsa: front:3: snd_pcm_drop No such device
Aug 22 23:36:45 calculus pipewire[18324]: mod.protocol-native: server 0x558df67c75c0: unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
Aug 22 23:36:45 calculus pipewire[18324]: pw.conf: 0x558df67885e0: could not load mandatory module "libpipewire-module-protocol-native": Resource temporarily unavailable
Aug 22 23:36:45 calculus pipewire[18324]: default: failed to create context: Resource temporarily unavailable
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Aug 22 23:40:22 calculus pipewire[578]: pw.node: (alsa_output.usb-Creative_Technology_Ltd_SB_Omni_Surround_5.1_000000H0-00.pro-output-2-106) suspended -> error (Start error: Invalid argument)
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:22 calculus pipewire[578]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: pw.node: (alsa_output.usb-Creative_Technology_Ltd_SB_Omni_Surround_5.1_000000H0-00.pro-output-2-106) suspended -> error (Start error: Invalid argument)
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:27 calculus pipewire[578]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Aug 22 23:40:32 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:32 calculus pipewire[578]: spa.alsa: Broken configuration: no configurations available: Invalid argument
Aug 22 23:40:32 calculus pipewire[578]: spa.alsa: Broken configuration for playback: no configurations available: Invalid argument
Aug 22 23:40:32 calculus pipewire[578]: pw.node: (alsa_output.usb-Creative_Technology_Ltd_SB_Omni_Surround_5.1_000000H0-00.pro-output-2-106) suspended -> error (Start error: Invalid argument)
Aug 22 23:52:04 calculus sddm-helper[35038]: pam_systemd(sddm-greeter:session): Failed to create session: Interrupted system call
Aug 22 23:52:04 calculus pipewire[578]: spa.alsa: 'hdmi:1,5': playback open failed: No such file or directory
Aug 22 23:52:04 calculus pipewire[578]: mod.adapter: usage: node.name=<string>
Aug 22 23:52:49 calculus p-steamos-priv-write[36820]: decline harder: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Aug 22 23:52:49 calculus p-steamos-priv-write[36840]: decline harder: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Aug 22 23:52:50 calculus p-steamos-priv-write[36863]: decline harder: 15000000 -> /sys/class/hwmon/hwmon4/power1_cap
Aug 22 23:52:50 calculus p-steamos-priv-write[36882]: decline harder: 15000000 -> /sys/class/hwmon/hwmon4/power2_cap
```

## `aplay -l` output
```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 1: ALC887-VD Digital [ALC887-VD Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: HDMI [HDA ATI HDMI], device 11: HDMI 5 [HDMI 5]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Controller [Wireless Controller], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: S51 [SB Omni Surround 5.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: S51 [SB Omni Surround 5.1], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: S51 [SB Omni Surround 5.1], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by jrcharney** [comment]
You wouldn't by chance be trying to connect a Soundblaster Omni Surround 5.1 trying to work, would you?

What does `cat /proc/asound/cards` look like?

**Comment by poperigby** [comment]
Yep, I'm using that. Sorry for forgetting to mention that.

Output of `cat /proc/asound/cards`:
```
 0 [Controller     ]: USB-Audio - Wireless Controller
                      Sony Interactive Entertainment Wireless Controller at usb-0000:00:14.0-7, full 
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7f20000 irq 128
 2 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xf7e60000 irq 129
 3 [S51            ]: USB-Audio - SB Omni Surround 5.1
                      Creative Technology Ltd SB Omni Surround 5.1 at usb-0000:00:14.0-8, full speed
```

**Comment by jrcharney** [comment]
Yeah, there's a lot of issues with that one. [Even PulseAudio made a `.conf` file for it](https://github.com/pulseaudio/pulseaudio/blob/master/src/modules/alsa/mixer/profile-sets/sb-omni-surround-5.1.conf).

Pipewire should support it because [this file](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/spa/plugins/alsa/mixer/profile-sets/sb-omni-surround-5.1.conf) exists.

I don't even use that card, and there is still a `/usr/share/alsa-card-profile/mixer/profile-sets/sb-omni-surround-5.1.conf` on my computer, which there should be on yours too.

Use `pacman -Ss` to check to make sure the `alsa-utils` package is installed.  Also check to make sure `pipewire` and `pipewire-pulse` packages are installed.

```
pacman -Ss alsa-utils
pacman -Ss pipewire
pacman -Ss pipewire-pulse
pacman -Ss alsa-card-profiles
```

Also take a look at what the following system control statuses look like.

```
systemctl --user status pipewire.socket
systemctl --user status pipewire.service
```

I doubt there is anything that shows up if you try `systemctl status pulseaudio`, but it wouldn't hurt to look. (This one might return nothing.)

My guesses are based on [this thread](https://bbs.archlinux.org/viewtopic.php?id=260372) on the Arch Linux Forum from a couple years ago.

**Comment by poperigby** [comment]
> I don't even use that card, and there is still a /usr/share/alsa-card-profile/mixer/profile-sets/sb-omni-surround-5.1.conf on my computer, which there should be on yours too.

Yeah, I have that too. Do you know if there's a way to check if it's actually using that file?

> Use `pacman -Ss` to check to make sure the `alsa-utils` package is installed. Also check to make sure `pipewire` and `pipewire-pulse` packages are installed.

```
$ pacman -Q alsa-utils pipewire pipewire-pulse alsa-card-profiles
alsa-utils 1.2.6-1
pipewire 1:0.3.50-2
pipewire-pulse 1:0.3.50-2
alsa-card-profiles 1:0.3.50-2
```

> Also take a look at what the following system control statuses look like.
> 
> ```
> systemctl --user status pipewire.socket
> systemctl --user status pipewire.service
> ```
> 
> I doubt there is anything that shows up if you try `systemctl status pulseaudio`, but it wouldn't hurt to look. (This one might return nothing.)
> 

```
$ systemctl --user status pipewire.socket
Aug 24 10:25:41 calculus systemd[430]: Listening on PipeWire Multimedia System Socket.
```
```
$ systemctl --user status pipewire.socket
Aug 24 10:25:43 calculus systemd[430]: Started PipeWire Multimedia Service.
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: could not set nice-level to -11: No such file or directory
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:25:43 calculus pipewire[563]: mod.rt: could not make thread 568 realtime using RTKit: No such file or directory
```
```
$ systemctl --user status pipewire-pulse
Aug 24 10:27:05 calculus systemd[430]: Started PipeWire PulseAudio.
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: could not set nice-level to -11: No such file or directory
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: RTKit error: org.freedesktop.DBus.Error.ServiceUnknown
Aug 24 10:27:05 calculus pipewire-pulse[4332]: mod.rt: could not make thread 4336 realtime using RTKit: No such file or directory
Aug 24 10:27:05 calculus pipewire-pulse[4335]: 536870912
Aug 24 10:27:06 calculus pipewire-pulse[4332]: mod.echo-cancel: aec.method is not supported anymore use library.name
```
```
$ systemctl status pulseaudio
Unit pulseaudio.service could not be found.
```

I also might mention that this wasn't working on Fedora Workstation or Silverblue when I tried those.

**Comment by jrcharney** [comment]
> I also might mention that this wasn't working on Fedora Workstation or Silverblue when I tried those.

ArchLinux is not a Fedora distribution, so I highly doubt that matters.

In terms of commands that might show what hardware you do have, `lspci -nnk` and `lsusb` are probably your best bets. `lspci` lists PCI devices like all the stuff that is plugged into your motherboard, while `lsusb` show USB devices. The first command might be more useful.

In terms of using that hardware, more than likely `systemctl` or `lspci` will tell you about the hardware, but it won't say if it uses the drivers.

I've been telling people for a while now: Don't go deleting files for things you think your computer doesn't have.  There is this temptation to do it because some people think they are conserving space, but those files are very small in comparison to the huge programs that might need them.

You should focus on the problem you have right now, not on making another problem because you decided to clean out files you didn't think you needed.

**Comment by poperigby** [comment]
Oh, I see how you could have misunderstood me. I wasn't asking that to figure out if I could delete it, I was asking that so I could figure out if the special configuration file was being loaded for my hardware.

```
$ lspci -mk
00:00.0 "Host bridge" "Intel Corporation" "Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers" -r07 "ASUSTeK Computer Inc." "Device 8694"
00:01.0 "PCI bridge" "Intel Corporation" "6th-10th Gen Core Processor PCIe Controller (x16)" -r07 "" ""
00:14.0 "USB controller" "Intel Corporation" "100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller" -r31 -p30 "ASUSTeK Computer Inc." "Device 8694"
00:16.0 "Communication controller" "Intel Corporation" "100 Series/C230 Series Chipset Family MEI Controller #1" -r31 "ASUSTeK Computer Inc." "Device 8694"
00:17.0 "SATA controller" "Intel Corporation" "Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]" -r31 -p01 "ASUSTeK Computer Inc." "Device 8694"
00:1c.0 "PCI bridge" "Intel Corporation" "100 Series/C230 Series Chipset Family PCI Express Root Port #5" -rf1 "" ""
00:1c.7 "PCI bridge" "Intel Corporation" "100 Series/C230 Series Chipset Family PCI Express Root Port #8" -rf1 "" ""
00:1d.0 "PCI bridge" "Intel Corporation" "100 Series/C230 Series Chipset Family PCI Express Root Port #9" -rf1 "" ""
00:1f.0 "ISA bridge" "Intel Corporation" "H110 Chipset LPC/eSPI Controller" -r31 "ASUSTeK Computer Inc." "Device 8694"
00:1f.2 "Memory controller" "Intel Corporation" "100 Series/C230 Series Chipset Family Power Management Controller" -r31 "ASUSTeK Computer Inc." "Device 8694"
00:1f.3 "Audio device" "Intel Corporation" "100 Series/C230 Series Chipset Family HD Audio Controller" -r31 "ASUSTeK Computer Inc." "Device 86c7"
00:1f.4 "SMBus" "Intel Corporation" "100 Series/C230 Series Chipset Family SMBus" -r31 "ASUSTeK Computer Inc." "Device 8694"
01:00.0 "VGA compatible controller" "Advanced Micro Devices, Inc. [AMD/ATI]" "Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]" -rc7 "ASUSTeK Computer Inc." "Device 0501"
01:00.1 "Audio device" "Advanced Micro Devices, Inc. [AMD/ATI]" "Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]" "ASUSTeK Computer Inc." "Device aaf0"
03:00.0 "Ethernet controller" "Realtek Semiconductor Co., Ltd." "RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller" -r15 "ASUSTeK Computer Inc." "PRIME B450M-A Motherboard"
```
```
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 041e:322c Creative Technology, Ltd SB Omni Surround 5.1
Bus 001 Device 003: ID 054c:09cc Sony Corp. DualShock 4 [CUH-ZCT2x]
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by jrcharney** [comment]
That's OK. I just wanted to make sure. Often a lot of problems usually are because somebody deleted something they didn't understand.

What I can tell, you have a desktop computer (`"PRIME B450M-A Motherboard"`), and from watching a couple of videos about the Creative Sound Blaster Omni 5.1 (let's just call it the SB Omni for the rest of this conversation), this is an external device that plugs into the USB port. I can relate to that, I have a Logitech G560 with LightSync, which I need to figure out how to manipulate the RGB controls.

Because the SB Omni is an external device, audio will come OUT of the various audio ports on the device, typically from the couple of headphone jacks in the front.  However, does it have a few other audio output options like a SPDIF for (fiber) optical connection which many soundbars have (though most of us will never use it), white and red RCA Audio jacks (typical of older speakers), and it has black and yellow audio jacks which connect to a subwoofer on a different channel.  Much of that is now obsolete technologically, but for hardcore audiophiles, they will still stick to all the analog stuff because they swear everything digital sounds "tinny", when in reality the reason why that happens is because older audio used lower quality compression.  I could go on about "square waves" and "Fourier transforms" and a whole bunch of other nerdy stuff, but that is beyond the scope of this issue.

Of course, many gamers still want this because they think they can hear somebody sneaking up behind them in CS:GO at the cost of that 5.1 Surround Sound.  In a 5.1 system, you have five speakers typically in front of you or to the side and one subwoofer for base boost.  If you turn off the surround sound just so you can hear that dude can sneak up behind you (which at that point just makes it a standard 2 channel system), then it defeats the purpose of having that surround sound especially since human ears typically hear better FORWARD than they do backward.

So what is wrong with your SB Omni?  Why isn't the sound coming out if there are drivers for it and the audio is being directed to go through the USB instead of any built-in speakers?  Do you have any headphones or speakers plugged into your SB Omni?

**Comment by jrcharney** [comment]
I know that's a lot of stuff to read that I just posted but just about everything you posted seems to indicate that everything should be working like it should, unless there is something that isn't plugged into the SB Omni for the audio to go out.

**Comment by poperigby** [comment]
Here, I'll try to explain my setup:

* I have a subwoofer, 3 forward speakers and 2 back speakers plugged into an amp
* A cable runs out of that amp to the SB Omni
* A USB cable runs from the SB Omni to the back of my PC

This was working on Windows, so I don't think there's anything wrong with the hardware.

Also, the SB Omni has a dial on it that is able to manipulate the volume in SteamOS. I'm not sure why that works but the sound doesn't. 

I tried plugging in some headphones to the PC and the sound was working through those.

I also don't even see an option for SB Omni digital output in the audio settings:
![image](https://user-images.githubusercontent.com/20866468/186971811-84b1a4ab-3957-4eaf-b03b-946dec8e7ae2.png)
