### ISSUE TITLE
I'm aware, an updated installer will be pushed later, sorry

### ISSUE THREAD

**Issue by theVakhovskeIsTaken** [holoiso-eol/holoiso#493]

**Comment by JimOkurku16** [comment]
ah I was about to make a post. I already wiped my main SSD drive so

**Comment by ryzendew** [comment]
Rip

**Comment by JimOkurku16** [comment]
> ah I was about to make a post. I already wiped my main SSD drive so

UPDATE: I've installed popOS,

I don't have a spare machine around, and since pacman was basically broken due to holoISO unable to download some items for pacman, I was basically stuck. I went to edit the pacman config file and I've removed the lines that were the issue (the stuff that made pacman not run were only holoISO files, and since there was already arch linux keys, I decided to remove the holoISO lines), and to my surprise, it actually worked, and I was able to install stuff. So I rushed into the terminal, wrote "sudo pacman -S firefox" clicked enter, it was promising... until it popped out saying "not enough disk space", I look into the live USB drive, and see around 150MB out of 256MB being filled up, so plan B, use the terminal to download neccesary files so I am not stuck in live USB forever, but issue with that, I had nowhere to put it, I wanted to originally format my HDD (which is 1TB), because I had no use for the stuff in there, yes there was an ubuntu iso, but when I tried downloading balena etcher using the terminal, I got an error message telling me it is read only. even under sudo. So plan B, since I can't really do much with the HDD, I looked elsewhere, I spotted that one partition on my SSD was 70GB free and it was mounted, so my immediate burning question, can we write files? and oh boy we can. I was so happy when I saw balena copying onto the SSD, and to my surprise it worked, and then I put a popOS iso in there, low and behold, I launched balena, and it couldnt do anything with the HDD, so I cant really write on the HDD, and my SSD stores all the files we need, and since my USB is the main drive for holoISO, there was only 1 way to go about it, albeit, extremely risky as I don't have a spare machine, I was kindoff hoping for everything to be in RAM already as it was live USB, so I decided to do it on my USB, and I am dead serious, balena etcher legit put popOS on that USB, the same USB that was the whole reason the liveUSB instance was running from, And I kid you not, it actually went through. popOS was on the USB, while holoUSB was basically just there sitting in RAM. I made sure I didn't shut down normally because obviously we dont really have a script or anything for shutting down, I mean we just formatted the entire liveUSB environment pretty much, So I just turned it off by pressing the power button, and I installed popOS, no issues. (ON THE SAME SSD).

**Comment by JesseKoldewijn** [comment]
Hey man, must say that at least to me the issue at hand doesn't seem all that clear. 

Are you having issues running the installer or something like that? Because from what it seems like you try to install packages yourself onto the liveboot which is both not ideal and not needed.

Can you maybe describe what you try to accomplish and maybe some system specifics so we could get an idea what you're working with?

Reason why I mention this is btw not to bash you (you get it... bash? jk) more because its not all to clear to me if you're still having issues of some sort.

**Comment by weclock-droid** [comment]
I'm glad you're aware. I'm not though.

**Comment by Grimish-ng** [comment]
Yes the 404 response is showing up in pacman. I believe the most frusterating part of this is realizing that when you go to settings where the update tab resides, gamescope takes a dump - just a pow dropout. No worries though. Its plain and simply due to a little hang that i'm certain will be resolved. Sometimes you got to take the good with the bad learn stillness sometimes.
