### ISSUE TITLE
Install on Steam Deck

### ISSUE THREAD

**Issue by InventorXtreme** [holoiso-eol/holoiso#633]
Is this a viable alternative to steamos itself on steam deck. I do not want the locked-down/wiped filesystem on a steamdeck, and want to use HoloISO on my steamdeck. Will features such as TDP limiting still work?

**Comment by oman2124** [comment]
This is meant to put Steam 3.0 on PC

**Comment by k1yrix** [comment]
Unfortunately, as mentioned, HoloISO is not meant to be on a Steam Deck. Using Valve's official recovery image is your best bet.

**Comment by theVakhovskeIsTaken** [comment]
> Is this a viable alternative to steamos itself on steam deck. I do not want the locked-down/wiped filesystem on a steamdeck, and want to use HoloISO on my steamdeck. Will features such as TDP limiting still work?

What works on your Deck right NOW, will work OOB on HoloISO without any edits required (altho screen refresh rate settings might be wonky for you)

**Comment by theVakhovskeIsTaken** [comment]
> Is this a viable alternative to steamos itself on steam deck. I do not want the locked-down/wiped filesystem on a steamdeck, and want to use HoloISO on my steamdeck. Will features such as TDP limiting still work?

What works on your Deck right NOW, will work OOB on HoloISO without any edits required (altho screen refresh rate settings might be wonky for you)

**Comment by Remzi1993** [comment]
> Is this a viable alternative to steamos itself on steam deck. I do not want the locked-down/wiped filesystem on a steamdeck, and want to use HoloISO on my steamdeck. Will features such as TDP limiting still work?

Why would you do this? I don't understand the need for it. You already got stable OS and bleeding edge updates directly from Valve. No need to install something else if you own a Steam Deck.

**Comment by DeviousFusion** [comment]
@Remzi1993 The reason why anyone would want to do this is that the SteamOS is an immutable system. You cannot install custom packages unless they are in an flatpak format and not every software is packaged as flatpak.

**Comment by Remzi1993** [comment]
> @Remzi1993 The reason why anyone would want to do this is that the SteamOS is an immutable system. You cannot install custom packages unless they are in an flatpak format and not every software is packaged as flatpak.

Yeah, that's also true 👍😅

**Comment by Merith-TK** [comment]
Well I am giving this a try right now, and will update as I go, I want to have an mutable system for myself where I can *properly* move my `/home` folder to my `sdcard` due to on the 64gb model, `/home` starts to acumulate junk files and there are no actual "Cleaners" for linux to remove that, and within about 2-3 months usage, these junk files consume all of the available storage on the deck's internal storage. 

Initial Problem, Starts in portrait mode, but that should be fixable long term due to mutability


UPDATE: Yeah that uh... seems to be the only issue so far, Steam launches in the appropriate orientation
legit this is a viable option if you want an mutable system in regards to your steamdeck
