### ISSUE TITLE
Unable to adjust tdp on steamdeck..

### ISSUE THREAD

**Issue by cloudsteamff** [holoiso-eol/holoiso#691]
Hi after flashing holoiso 3.4 and updating everything i have one problem with my steam deck hardware. I can set fps limit and refresh rate with steam menu but i'm still unable to change tdp limit for cpu and gpu. They basically do nothing.  it's written that tdp should work in steamdeck in your guide. Thanks

**Comment by AllyTheProtogen** [comment]
Did you try to use HoloISO on your actual steam deck? If so, I wouldn't recommend doing that. I really suggest using valves steam deck recovery image provided [here](https://help.steampowered.com/en/faqs/view/1b71-edf2-eb6d-2bb3). It may say that actual steam deck hardware works with HoloISO(and it should afaik since everything is from valves repos) but imo it's really best to just use the recovery image. I hope I was able to help!

**Comment by cloudsteamff** [comment]
Holoiso on deck works perfectly. I used it because it let me install and update within a sd card since normal steam deck doesn't (i have win 10 on internal nvme). I would really really love to know how to enable tdp bar man.. maybe with a konsole command. Thanks for your patience :)

**Comment by kramlat** [comment]
crankshaft has been abandoned in favor of deckyloader. Deckyloader also has a tdp plugin as well and it works on newer versions of steamos. the audo loader plugin for an example seems to work even better on holoiso installed on a steam deck. Also, one cannot install both crankshaft and deckyloader at the same time anyways.
