### ISSUE TITLE
Doesn't boot, the UEFI partition don't see in the bios

### ISSUE THREAD

**Issue by JohnPetrucci** [holoiso-eol/holoiso#694]
## Your Issue:
Doesn't boot, the UEFI partition I don't see in the bios
*type your problem here*
After Installation in SDA internal, he don't boot and bios "message to setting an CSM, but i try to set enable,disable, auto" the UEFI partition don't see in the bios.
Please Fix the problem

## Your device's full specs
MB; asus p8h61 
CPU: I7 3770
GPU: AMD RX 5700
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot19700101_1011-beta2a
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
yeah pubg crash bhai
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by ch3wy** [comment]
Had the same issue with a 4th gen Intel CPU, only way I've figured out to boot the installation is by installing rEFInd onto a flash drive and booting from the flash drive into the installation.

My setup is a game cabinet so I don't really care about the USB drive always having to be plugged up to boot since it'll be out of view and reach anyway.
