### ISSUE TITLE
[Report] Stuck at "grub>" command line after first install on anbernic win600

### ISSUE THREAD

**Issue by austrasien** [holoiso-eol/holoiso#695]
## Your Issue:
I'm stuck after installing HoloIso (and first restart of the device) with a command line screen indicating "grub>"

*type your problem here*
1. install HoloIso with a fresh installation on an Anbernic Win600
2. when installation successfully finishes and asks user to restart device, shut down the device
3. remove the bootable usb key
4. start the machine
5. then a command line with "grub>" appears and the SteamOS interface don't load.

## Your device's full specs
Anbernic Win600 3020e
CPU: AMD Athlon Silver 3020e Dali
GPU: AMD Radeon RX Vega 3

## Your OS version
HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64

**Comment by kramlat** [comment]
I have had that happen on a steam deck. I solved it by unplugging my usb sick, plugging it back in, and restarting the deck. from there, I booted off the usb stick again and I installed it successfully. this time I got the OOBE as expected. I also chose "deck" for the username in both instances so that I can fool the installer for deckyloader into thinking that the valve version was installed and oddly audio loader works even better on holoiso than on vanilla steamos. I also like the freedom I have gotten by not having a readonly root directory.
