### ISSUE TITLE
[can not install steamOS due to ACPI ERROR]

### ISSUE THREAD

**Issue by chaoyangfan-lgi** [holoiso-eol/holoiso#701]
## Your Issue: 
```
BIOS error: could not resolve symbol: [\_SB.PCI0.GP17.VGA.LCD._BCMN7] AE_NOT_FOUND
ACPI ERROR: Aborting method \_SB.PCI0..GP17.VGA.LCD._BCM due to previouss error. It seems the hardware is too new to install steamOS. It there any hard limitation of installing steamOS. I did not find the information at github.
```

## Your device's full specs
```
CPU: amd r7 5800
GPU: gtx 3070
```

**Comment by MonkaKokosowa** [comment]
Have you tried using `acpi_backlight=vendor` in kernel parameters? I think I remember there being an issue with BIOS versions or something similiar with that error.

**Comment by mikevskiy** [comment]
> ## Your Issue:
> 
> ```
> BIOS error: could not resolve symbol: [\_SB.PCI0.GP17.VGA.LCD._BCMN7] AE_NOT_FOUND
> ACPI ERROR: Aborting method \_SB.PCI0..GP17.VGA.LCD._BCM due to previouss error. It seems the hardware is too new to install steamOS. It there any hard limitation of installing steamOS. I did not find the information at github.
> ```
> 
> ## Your device's full specs
> 
> ```
> CPU: amd r7 5800
> GPU: gtx 3070
> ```

solved this error?

**Comment by Bryan199234** [comment]
> Have you tried using `acpi_backlight=vendor` in kernel parameters? I think I remember there being an issue with BIOS versions or something similar to that error.

Educate me here: the board's BIOS version is a dependency when installing Holo? I'm running a build fairly similar to OP, the difference being that mine is an Intel i7 CPU. I also may not be receiving BIOS updates since switching, and I personally don't know how and haven't even looked into it.
If I were to figure out how to update versions, could that update break my installed image?
