### ISSUE TITLE
Cant download anything from Flatpak? always reset by peers

### ISSUE THREAD

**Issue by hawari21** [holoiso-eol/holoiso#742]
Long story short i install Steam OS with latest offline installer and everything was good, until i tried to install firefox and a message pops up "Aborted due to faillure (While downloading https://ciscobinary.openh264.org/libopenh264-2.2.0-linux64.6.bz2: Error receiving data : Connection reset by peers".Yes, my internet are working just fine download steam update also work, and i tried to update HoloSteam which hopping to solve this case but it wont download anything. Is there anything i could do?

**Comment by Hideiuke** [comment]
Go ChimeraOS, SteamOS is not for PC's.

**Comment by AngelQC** [comment]
The current state of the installer ISO (the Dec. 22 v4 official one) is very flaky, I reinstalled over a month ago and had to jump into loops in order to successfully install it again.  
- pacman.conf needs to be edited to sync repo names (adding "-main" at the end, on everything but holoiso-stable)
- The installer script must be modified in order to correct:
-- Remove the partitioning for /home if you want to keep it btrfs (automatically partition/format as ext4 despite root being btrfs)
-- If you still have a version of holoiso installed on another drive (I kept it to refer to it in case I forgot something), it will mistakenly be used, I think there is an issue with the search made with partition names.
- Also, you need extra steps in order to re-generate the pacman keys
Not easy to spot, but I've been running quite ok since
