### ISSUE TITLE
Holoiso installation to MicroSD card appears to "kill" it

### ISSUE THREAD

**Issue by bookmarks1983** [holoiso-eol/holoiso#778]
I've tried installing Holoiso (from a USB drive) to a MicroSD card on the Steam Deck, and it did work twice (both on SanDisk extreme 64gb, 128gb) on the previous release. However the latest release appears to render MicroSD cards unwritable. 

I've sent 4 MicroSD cards (SanDisk Extreme and Ultra, Samsung EVO) to RMA, some twice, that the distributor was starting to suspect I was doing something fishy with the cards. 

The install (from a USB drive to the microSD mmcblk0) proceeds as usual but after reboot the MicroSD does not show up on the boot menu as in previous version's installs. Two partitions show up in partition manager but they cannot be removed or formatted (Windows or linux). Writing 0 or 1s onto the card directly doesnt work either. A retry install will end up in error as the MicroSD card has been rendered read-only for some strange reason. Has anyone tried installing to a microSD and had the same happen to them?

**Comment by GreatestMuslim** [comment]
ANY Linux installation on a MicroSD Card will kill it.

**Comment by TwoD** [comment]
@GreatestMuslim Got any evidence for that or is it just an unfounded conclusion? There are countless devices running Linux from SD cards just fine (tens of millions of Raspberry Pi devices out there to count a few).

I haven't tried this with HoloISO but I don't see why anything specific in the install itself would cause the card to die so soon, unless it's doing excessive amounts of writes. SDs have poor support for error compensation or wear-leveling.
Long term I don't think it's ideal to install something to an SD card which isn't specifically designed for it, for the above reasons. OS:es which do not expect to be installed on an SD card will most likely assume they can do things like writing logs, access info, and various other types of high-frequency data all over the card.

There is a chance the reader/writer device is the issue. I've got a phone which "ate" three SD-cards before the fourth one worked. They would read/write just fine for after being put into the device and then completely die about a day later after taking some photos. I didn't bother RMA:ing the cards or the phone, but also didn't use a card in it for about a year  before trying again. It has been stable since (but haven't dared taking it out more than a few times). Could have been a firmware upgrade which fixed some issue on my phone where it did something funky instead of "just" writing the photos to it.
For the Deck, I would most likely have put the installation on a removable USB drive instead of an SD card. Less likely to cause long term issues, and most likely much faster.

**Comment by bookmarks1983** [comment]
@TwoD Thanks for replying! I wasn't planning on responding to the previous reply. I've installed Linux countless times to various devices (including RPis since the first iteration, and other brands like Odroid, NanoPi, BananaPi, OrangePi etc) and never has a MicroSD been rendered unwritable like that. 

The thing is that it worked fine with the previous version of HoloISO and the problem can be consistently recreated with the current verison. I do not think an excessive amount of writes are causing the issue as the cards are new (which includes the replacement from the RMA). It's most likely not an issue with the card reader in my Steam Deck as my other MicroSD cards (x10) of the same brand and capacity are working fine in it with Windows and SteamOS.

I agree that MicroSD cards are not ideal for an OS and I've given up trying to install HoloISO to it, but I think that this MicroSD card "killing" behaviour shouldn't happen in the first place. Though I suppose this shouldn't be an issue since noone else appears to be trying to (or need to) install HoloISO to a MicroSD.
