### ISSUE TITLE
intel 12th gen and RX 7600

### ISSUE THREAD

**Issue by natsukirei** [holoiso-eol/holoiso#783]
Hey guys

I have a small form factor rig which I want to turn into a steam deck like console on my TV

I was wondering if the RX 7600 and intel 12th gen hardware is compatible , I did see someone ask in Feb but that was a whole ago who used chimera OS instead

**Comment by natsukirei** [comment]
well i tried, sadly i cant get it to boot with an AMD RX 7600, the ISO/kernel is probably out of date and i cant find an updated ISO

Chimera OS works but its not true steam OS like HoloISO :(

**Comment by zweiler2** [comment]
I made a fork of HoloISO and it has Arch's 6.3 Kernel with MESA 23.1.1 [here](https://github.com/zweiler2/HoloISO_Tweaked).  
RX 7900 GPUs are confirmed to work, so RX 7600 should too.  
If you face any issues with my fork, please report them on my page and not here.

**Comment by natsukirei** [comment]
> I made a fork of HoloISO and it has Arch's 6.3 Kernel with MESA 23.1.1 [here](https://github.com/zweiler2/HoloISO_Tweaked). RX 7900 GPUs are confirmed to work, so RX 7600 should too. If you face any issues with my fork, please report them on my page and not here.

Runs beautifully, the only issue im having is the mouse cursor, im using a logitech G603 and theirs no cursor on the screen, i can move the mouse but im flying blind lol

Ive done some reading, apparently its an AMD driver issue with X11 and you need to use Wayland or something idk im no pro

**Comment by zweiler2** [comment]
On desktop i assume?  
Talked to one who had the same issue but he fixed it by setting the mouse cursor to software rendering by creating [this file](https://github.com/HoloISO/holoiso/commit/9c47321a3819045e72944553ad5ef5469cd7fabc) which as you can see i integrated into the ISO and now you are saying otherwise.... Interesting...  
Try deleting that file and relogin (don't restart).
If the issue persists then please create an issue on my page.
