### ISSUE TITLE
Cpu + GPU combo work for Steam OS?

### ISSUE THREAD

**Issue by Hotsuna** [holoiso-eol/holoiso#798]
Only reason I'm asking is that is says it needs to be compatible with something else instead of Radeon so I wanted to ask to make sure.  My combo for the mini itx build is Ryzen 5 7600x and a Rx 6800.  Thank you guys in advance!

**Comment by Grimish-ng** [comment]
I think you would be pretty good with that. Has very good amdgpu support and since you'll be using mesa I think you'll have a pretty good experience. You may run into some issues on your Ryzen 7600x and kernel compatability because holoiso ships with a kernel that doesn't really move forward - much like the steamdeck itself.

**Comment by Hotsuna** [comment]
So after starting the installer, it stops on this line "hub 10-0:1.0: config failed, hub doesn't have any ports"

**Comment by apprenticeofbabel** [comment]
The current release of holoiso has an old version of the Linux Kernel and Mesa. That creates major issues with the recent 7000 series CPU's. I have experienced the same problem with my 7700X. It's likely to be the integrated graphics that is causing this hang on boot. You could try to turn off the iGPU and see if that makes any difference.

If you don't find a way but still want to run holoiso you could use the tweaked version by zweiler2. Otherwise It's either waiting for an updated release or using a different system.

**Comment by michailromanov** [comment]
I have a 5600G and an RX6600 ^^
