### ISSUE TITLE
Download page not working 

### ISSUE THREAD

**Issue by A53o** [holoiso-eol/holoiso#864]
## Your Issue: Download page not working

![Screenshot_20240102_185306](https://github.com/HoloISO/holoiso/assets/146792539/a0cead46-f1c8-445e-ab58-9182f3e59848)

**Comment by Querzion** [comment]
![image](https://github.com/HoloISO/holoiso/assets/39269026/074ad9ab-6d29-4504-820f-7da6de147d32)

**Comment by ExplosiveGeek77** [comment]
https://web.archive.org/web/20240111180316/https://cd2.holoiso.ru.eu.org/HoloISO_5.0.1_stable-20230823_f3bbb0d973_release-1-x86_64.iso

**Comment by KP2048** [comment]
> https://web.archive.org/web/20240111180316/https://cd2.holoiso.ru.eu.org/HoloISO_5.0.1_stable-20230823_f3bbb0d973_release-1-x86_64.iso

That doesn't work because downloads bigger than the maximum 32 bit signed integer cause an integer overflow in the wayback machine, causing the download to stall if it seeks anywhere past that limit. Essentially files bigger than about 2.1 Gb don't work. The only real solution is for the dev to fix their cdn
